package main
import("fmt";"bytes";"context";"encoding/binary";"errors";"io";"net";"net/http";"sync";"testing";"time")
type roundFunc func(*http.Request)(*http.Response,error)
func(f roundFunc)RoundTrip(r *http.Request)(*http.Response,error){return f(r)}
func query()[]byte{return []byte{1,2,1,0,0,1,0,0,0,0,0,0,1,'a',0,0,1,0,1}}
func answer(q []byte)[]byte {b:=append([]byte(nil),q...);b[2]=129;b[3]=128;b[7]=1;return append(b,192,12,0,1,0,1,0,0,0,60,0,4,1,2,3,4)}
func TestExitIsolationAndCache(t *testing.T){
 var mu sync.Mutex;calls:=map[int]int{};r:=&relay{config:Config{DirectName:"direct.test",PrivateName:"private.test",Devices:map[string]int{"192.168.7.101":12600,"192.168.7.102":12601}},clients:map[int]*http.Client{},cache:map[string]entry{},slots:make(chan struct{},64)}
 for _,port:=range []int{0,12600,12601}{port:=port;r.clients[port]=&http.Client{Transport:roundFunc(func(req *http.Request)(*http.Response,error){mu.Lock();calls[port]++;mu.Unlock();q,_:=io.ReadAll(req.Body);b:=answer(q);b[len(b)-1]=byte(port%100);return &http.Response{StatusCode:200,Body:io.NopCloser(bytes.NewReader(b))},nil})}}
 for _,ip:=range []string{"192.168.7.101","192.168.7.102","192.168.7.103"}{q:=query();b:=r.resolve(q,ip);port:=r.config.Devices[ip];if b[len(b)-1]!=byte(port%100){t.Fatal("wrong DNS exit",ip)};q[0]=42;b=r.resolve(q,ip);if b[0]!=42 || calls[port]!=1{t.Fatal("cache or transaction ID failed")}}
 for k,v:=range r.cache{v.created=time.Now().Add(-3*time.Second);r.cache[k]=v};b:=r.resolve(query(),"192.168.7.101");if binary.BigEndian.Uint32(b[25:29])!=57{t.Fatal("TTL did not age")}
}
func TestFailureNeverFallsBack(t *testing.T){r:=&relay{config:Config{PrivateName:"private.test",Devices:map[string]int{"client":12600}},clients:map[int]*http.Client{12600:{Transport:roundFunc(func(*http.Request)(*http.Response,error){return nil,errors.New("proxy down")})},0:{Transport:roundFunc(func(*http.Request)(*http.Response,error){t.Fatal("fell back to direct");return nil,nil})}},cache:map[string]entry{},slots:make(chan struct{},1)};b:=r.resolve(query(),"client");if b[3]&15!=2{t.Fatal("expected SERVFAIL")};if r.resolve([]byte{1},"client")!=nil{t.Fatal("malformed DNS accepted")}}
func TestSocksPinnedEndpoint(t *testing.T){l,e:=net.Listen("tcp4","127.0.0.1:0");if e!=nil{t.Fatal(e)};defer l.Close();done:=make(chan error,1);go func(){c,e:=l.Accept();if e!=nil{done<-e;return};defer c.Close();b:=make([]byte,3);io.ReadFull(c,b);c.Write([]byte{5,0});b=make([]byte,10);io.ReadFull(c,b);if !bytes.Equal(b,[]byte{5,1,0,1,9,9,9,9,1,187}){done<-errors.New("wrong destination");return};c.Write([]byte{5,0,0,1,0,0,0,0,0,0});done<-nil}();cfg:=Config{Exits:map[string]string{"12600":fmt.Sprintf("socks5://127.0.0.1:%d",l.Addr().(*net.TCPAddr).Port)}};exits,e:=makeExits(cfg);if e!=nil{t.Fatal(e)};r:=&relay{exits:exits};c,e:=r.privateDial(context.Background(),12600,"9.9.9.9");if e!=nil{t.Fatal(e)};c.Close();if e=<-done;e!=nil{t.Fatal(e)}}
