#!/bin/sh /etc/rc.common
USE_PROCD=1
START=96
STOP=9
start_service(){
  [ "$(uci -q get fastacl251.main.enabled)" = 1 ] || return 0
  procd_open_instance
  procd_set_param command /usr/bin/fastacl251 guard
  procd_set_param respawn 3600 5 5
  procd_close_instance
}
stop_service(){ /usr/bin/fastacl251 stop; }
service_triggers(){ procd_add_reload_trigger fastacl251 firewall; }
