#!/bin/sh
/usr/bin/install-proxy-realtime-ip-suite >/tmp/install-proxy-realtime-ip-suite.log 2>&1 || {
  logger -t proxy-realtime-ip "install failed, see /tmp/install-proxy-realtime-ip-suite.log"
  exit 1
}
exit 0
